Repository mojohaus/flatten-maven-plugin, pull requests merged in 2022-08, with the labels that each got.

#289 #288 Add configuration option to omit dependency exclusions stanzas from flattened POM
  src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
  src/test/java/org/codehaus/mojo/flatten/FlattenMojoOmitExclusionsTest.java
  src/test/resources/omit-exclusions/pom.xml
Labels: enhancement

#293 Remove outdated CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: maintenance

#294 Reorder items in pom.xml to meet code style conventions
  pom.xml
Labels: maintenance

#297 GH actions - testing for Maven 3.2.5, 3.8.6
  .github/workflows/maven.yml
  src/it/projects/complete-multimodule-parent-pom-cifriendly/invoker.properties
Labels: build

#298 Use Maven Core artifacts in provided scope
  pom.xml
  src/main/java/org/codehaus/mojo/flatten/model/resolution/ReactorModelPool.java
Labels: maintenance

#299 Cleanup - use project configuration from parent
  README.md
  pom.xml
  src/site/site.xml
Labels: maintenance

#301 Bump junit in IT test
  src/it/projects/resolve-projects-in-reactor/bom/pom.xml
  src/it/projects/resolve-projects-in-reactor/verify.groovy
Labels: dependencies

#302 Bump Guava in IT tests
  src/it/projects/bom-flattenMode/bom/pom.xml
  src/it/projects/bom-pomElements/bom/pom.xml
Labels: dependencies

#300 Move Contributors to dedicated pom section
  pom.xml
Labels: maintenance

#303 Cleanup diamond <> operator
  src/main/java/org/codehaus/mojo/flatten/Dependencies.java
  src/main/java/org/codehaus/mojo/flatten/FlattenDescriptor.java
  src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
  src/main/java/org/codehaus/mojo/flatten/cifriendly/CiInterpolatorImpl.java
  src/main/java/org/codehaus/mojo/flatten/cifriendly/CiModelInterpolator.java
  src/main/java/org/codehaus/mojo/flatten/model/resolution/ReactorModelPool.java
Labels: maintenance

#304 Use replace for non regular expression replace
  src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
Labels: maintenance

#296 Fix issue #291 Use scope/optional of profile dep over default
  src/it/projects/profile-with-deps-inherit-parent-depMgmt-jdk-optional-in-profile/parent/pom.xml
  src/it/projects/profile-with-deps-inherit-parent-depMgmt-jdk-optional-in-profile/pom.xml
  src/it/projects/profile-with-deps-inherit-parent-depMgmt-jdk-optional-in-profile/verify.groovy
  src/it/projects/profile-with-deps-inherit-parent-depMgmt-jdk-scope-in-profile/parent/pom.xml
  src/it/projects/profile-with-deps-inherit-parent-depMgmt-jdk-scope-in-profile/pom.xml
  src/it/projects/profile-with-deps-inherit-parent-depMgmt-jdk-scope-in-profile/verify.groovy
  src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
Labels: bug

#306 Fix copypaste errors in ITs projects
  src/it/projects/profile-with-deps-inherit-parent-depMgmt-test/parent/pom.xml
  src/it/projects/profile-with-deps-inherit-parent-depMgmt-test/pom.xml
Labels: maintenance

#305 Bump maven-dependency-tree from 2.2 to 3.1.1
  pom.xml
  src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
Labels: dependencies

#270 Keep comments in .flattened-pom.xml
  src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
  src/main/java/org/codehaus/mojo/flatten/KeepCommentsInPom.java
  src/test/java/org/codehaus/mojo/flatten/KeepCommentsInPomTest.java
  src/test/resources/keep-comments-in-pom/expected-flattened-pom-jdk11.xml
  src/test/resources/keep-comments-in-pom/expected-flattened-pom.xml
  src/test/resources/keep-comments-in-pom/pom.xml
Labels: enhancement

#281 Set `project.originalModel` after flattening
  src/it/projects/flatten-shaded-drp/invoker.properties
  src/it/projects/flatten-shaded-drp/pom.xml
  src/it/projects/flatten-shaded-drp/src/main/java/com/example/Main.java
  src/it/projects/flatten-shaded-drp/verify.groovy
  src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
Labels: bug

#310 Enable checkstyle verification during build
  pom.xml
  src/main/java/org/codehaus/mojo/flatten/CleanMojo.java
  src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
  src/main/java/org/codehaus/mojo/flatten/KeepCommentsInPom.java
  src/main/java/org/codehaus/mojo/flatten/ModelBuilderThreadSafetyWorkaround.java
  src/main/java/org/codehaus/mojo/flatten/cifriendly/CiInterpolatorImpl.java
  src/main/java/org/codehaus/mojo/flatten/cifriendly/CiModelInterpolator.java
  src/main/java/org/codehaus/mojo/flatten/model/resolution/FlattenModelResolver.java
  src/main/java/org/codehaus/mojo/flatten/model/resolution/ReactorModelPool.java
  src/test/java/org/codehaus/mojo/flatten/CreateEffectivePomTest.java
  src/test/java/org/codehaus/mojo/flatten/FlattenMojoOmitExclusionsTest.java
  src/test/java/org/codehaus/mojo/flatten/FlattenMojoTest.java
  src/test/java/org/codehaus/mojo/flatten/KeepCommentsInPomTest.java
Labels: enhancement

#313 Execute integration test only when run-its profile is set
  pom.xml
Labels: maintenance
