Repository mojohaus/flatten-maven-plugin, pull requests merged in 2023-03, with the labels that each got.

#344 Upgrade Maven versions used on GitHub 3.8.7 -> 3.8.8, 3.9.0 -> 3.91
  .github/workflows/maven.yml
Labels: build

#346 Enable spotless plugin - automatic code formatting
  pom.xml
  src/main/java/org/codehaus/mojo/flatten/AbstractFlattenMojo.java
  src/main/java/org/codehaus/mojo/flatten/CleanMojo.java
  src/main/java/org/codehaus/mojo/flatten/Dependencies.java
  src/main/java/org/codehaus/mojo/flatten/DirectDependenciesInheritanceAssembler.java
  src/main/java/org/codehaus/mojo/flatten/ElementHandling.java
  src/main/java/org/codehaus/mojo/flatten/FlattenDependencyMode.java
  src/main/java/org/codehaus/mojo/flatten/FlattenDescriptor.java
  src/main/java/org/codehaus/mojo/flatten/FlattenMode.java
  src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
  src/main/java/org/codehaus/mojo/flatten/KeepCommentsInPom.java
  src/main/java/org/codehaus/mojo/flatten/LoggingModelProblemCollector.java
  src/main/java/org/codehaus/mojo/flatten/ModelBuilderThreadSafetyWorkaround.java
  src/main/java/org/codehaus/mojo/flatten/PomProperty.java
  src/main/java/org/codehaus/mojo/flatten/cifriendly/CiInterpolator.java
  src/main/java/org/codehaus/mojo/flatten/cifriendly/CiInterpolatorImpl.java
  src/main/java/org/codehaus/mojo/flatten/cifriendly/CiModelInterpolator.java
  src/main/java/org/codehaus/mojo/flatten/model/resolution/FlattenModelResolver.java
  src/main/java/org/codehaus/mojo/flatten/model/resolution/ReactorModelPool.java
  src/test/java/org/codehaus/mojo/flatten/CreateEffectivePomTest.java
  src/test/java/org/codehaus/mojo/flatten/FlattenMojoOmitExclusionsTest.java
  src/test/java/org/codehaus/mojo/flatten/FlattenMojoTest.java
  src/test/java/org/codehaus/mojo/flatten/KeepCommentsInPomTest.java
Labels: maintenance

#347 Move CiModelInterpolator to JSR-330 component
  src/main/java/org/codehaus/mojo/flatten/cifriendly/CiModelInterpolator.java
  src/main/resources/META-INF/plexus/components.xml
Labels: maintenance

#350 Fix #348 - Use repositories defined in project for artifact resolving
  src/it/mrm/settings-no-mirror.xml
  src/it/projects/issue-348-repository-from-project/invoker.properties
  src/it/projects/issue-348-repository-from-project/pom.xml
  src/it/projects/issue-348-repository-from-project/verify.groovy
  src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
Labels: bug

#351 Update Maven to 3.5.0
  .github/workflows/maven.yml
  pom.xml
  src/it/projects/bom-flattenMode/pom.xml
  src/it/projects/bom-pomElements/pom.xml
  src/it/projects/complete-artifact-pom/pom.xml
  src/it/projects/complete-artifact-pom/verify.groovy
  src/it/projects/complete-mavenplugin-pom/pom.xml
  src/it/projects/complete-mavenplugin-pom/verify.groovy
  src/it/projects/complete-multimodule-parent-pom-cifriendly/pom.xml
  src/it/projects/complete-multimodule-parent-pom-cifriendly/verify.groovy
  src/it/projects/complete-multimodule-parent-pom-direct-dependencies/pom.xml
  src/it/projects/complete-multimodule-parent-pom-direct-dependencies/verify.groovy
  src/it/projects/complete-multimodule-parent-pom/pom.xml
  src/it/projects/complete-multimodule-parent-pom/verify.groovy
  src/it/projects/external-parent/pom.xml
  src/it/projects/external-parent/verify.groovy
  src/it/projects/issue-348-repository-from-project/pom.xml
  src/it/projects/issue-348-repository-from-project/verify.groovy
  src/it/projects/jdk-profile-inactive/pom.xml
  src/it/projects/jdk-profile-inactive/verify.groovy
  src/it/projects/optional-elements-modeMinimum/pom.xml
  src/it/projects/optional-elements-modeMinimum/verify.groovy
  src/it/projects/optional-elements-modeOss/pom.xml
  src/it/projects/optional-elements-modeOss/verify.groovy
  src/it/projects/optional-elements-modeOssrh/pom.xml
  src/it/projects/optional-elements-modeOssrh/verify.groovy
  src/it/projects/optional-elements-pomElements-legacy/pom.xml
  src/it/projects/optional-elements-pomElements-legacy/verify.groovy
  src/main/java/org/codehaus/mojo/flatten/model/resolution/FlattenModelResolver.java
Labels: enhancement
