Repository mojohaus/flatten-maven-plugin, pull requests merged in 2024-01, with the labels that each got.

#393 Fix next ITs for Maven 4
  .gitignore
  src/it/mrm/repository/parent-deps-1.1.pom
  src/it/projects/no-overwrite-3.6.3-later/invoker.properties
  src/it/projects/no-overwrite-4.0.0-later/.flattened-pom.xml
  src/it/projects/no-overwrite-4.0.0-later/invoker.properties
  src/it/projects/no-overwrite-4.0.0-later/pom.xml
  src/it/projects/no-overwrite-4.0.0-later/verify.groovy
Labels: bug

#394 Use Maven 3.9.6 for build
  .github/workflows/maven.yml
Labels: build

#371 Make the default operation configurable
  src/main/java/org/codehaus/mojo/flatten/FlattenDescriptor.java
  src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
Labels: enhancement

#396 Use Shared ASF Action from Release Drafter - fix
  .github/workflows/release-drafter.yml
Labels: build

#398 Use default config for build
  .github/workflows/maven.yml
Labels: build

#399 Require Maven 3.6.3 as minimum
  pom.xml
  src/test/resources/keep-comments-in-pom/expected-flattened-pom-jdk11.xml
  src/test/resources/keep-comments-in-pom/expected-flattened-pom.xml
  src/test/resources/keep-comments-in-pom/pom.xml
Labels: enhancement
