Repository mojohaus/flatten-maven-plugin, pull requests merged in 2025-06, with the labels that each got.

#453 Fix FilteringValueSourceWrapper for a newer version of plexus-interpolation, Maven 3.9.10
  src/main/java/org/codehaus/mojo/flatten/extendedinterpolation/FilteringValueSourceWrapper.java
  src/test/java/org/codehaus/mojo/flatten/extendedinterpolation/ExtendedStringSearchModelInterpolatorTest.java
Labels: bug

#446 Fix #400 - Preserve POM content ordering (and formatting) on resolveCiFriendliesOnly flattenMode
  src/main/java/org/codehaus/mojo/flatten/FlattenMojo.java
  src/main/java/org/codehaus/mojo/flatten/PomProperty.java
  src/main/java/org/codehaus/mojo/flatten/cifriendly/CiInterpolatorImpl.java
  src/main/java/org/codehaus/mojo/flatten/cifriendly/CiModelInterpolator.java
  src/test/java/org/codehaus/mojo/flatten/KeepCommentsInPomTest.java
  src/test/resources/keep-comments-in-pom/expected-flattened-pom-jdk11.xml
  src/test/resources/keep-comments-in-pom/expected-flattened-pom.xml
  src/test/resources/keep-comments-in-pom/pom.xml
Labels: bug

#456 Rename 'Goals' to 'Plugin Documentation' in site manu
  src/site/site.xml
Labels: documentation

#458 Fix typo in License name
  pom.xml
Labels: maintenance

#459 Remove a dead link to MOJO-2030 from documentation
  src/main/java/org/codehaus/mojo/flatten/CleanMojo.java
Labels: documentation
